const PRODUCTS = [
  { "id": 1, "name": "Soup - Campbells, Cream Of", "price": 5.01, "stock": 5 },
  { "id": 2, "name": "Rosemary - Fresh", "price": 1.44, "stock": 5 },
  { "id": 3, "name": "V8 Splash Strawberry Banana", "price": 2.61, "stock": 4 },
  { "id": 4, "name": "Table Cloth 120 Round White", "price": 3.8, "stock": 4 },
  { "id": 5, "name": "Butter Balls Salted", "price": 9.89, "stock": 0 },
  { "id": 6, "name": "Chicken - Base, Ultimate", "price": 17.75, "stock": 8 },
  { "id": 7, "name": "Flower - Commercial Spider", "price": 10.78, "stock": 0 },
  { "id": 8, "name": "Edible Flower - Mixed", "price": 10.75, "stock": 0 },
  { "id": 9, "name": "Soup - Base Broth Chix", "price": 19.35, "stock": 0 },
  { "id": 10, "name": "Cheese - Brie,danish", "price": 3.24, "stock": 5 },
  { "id": 11, "name": "Pepper - Black, Whole", "price": 12.34, "stock": 7 },
  { "id": 12, "name": "Zucchini - Green", "price": 7.19, "stock": 3 },
  { "id": 13, "name": "Spice - Chili Powder Mexican", "price": 16.97, "stock": 7 },
  { "id": 14, "name": "Lettuce - Frisee", "price": 15.72, "stock": 9 },
  { "id": 15, "name": "Pork - Back, Short Cut, Boneless", "price": 18.02, "stock": 1 },
  { "id": 16, "name": "Browning Caramel Glace", "price": 13.19, "stock": 5 },
  { "id": 17, "name": "Wine - White, Cooking", "price": 5.65, "stock": 7 },
  { "id": 18, "name": "Compound - Pear", "price": 18.7, "stock": 2 },
  { "id": 19, "name": "The Pop Shoppe Pinapple", "price": 4.07, "stock": 0 },
  { "id": 20, "name": "Compound - Rum", "price": 6.03, "stock": 3 },
  { "id": 21, "name": "Wasabi Paste", "price": 8.89, "stock": 7 },
  { "id": 22, "name": "Scallops - In Shell", "price": 1.09, "stock": 10 },
  { "id": 23, "name": "Lid - 10,12,16 Oz", "price": 2.95, "stock": 8 },
  { "id": 24, "name": "Corn - On The Cob", "price": 5.06, "stock": 3 },
  { "id": 25, "name": "Wine - Cabernet Sauvignon", "price": 14.97, "stock": 9 },
  { "id": 26, "name": "Lobster - Live", "price": 9.73, "stock": 9 },
  { "id": 27, "name": "Tomatoes - Cherry", "price": 18.95, "stock": 0 },
  { "id": 28, "name": "Cheese - Mascarpone", "price": 5.16, "stock": 0 },
  { "id": 29, "name": "Chicken - Wings, Tip Off", "price": 6.92, "stock": 0 },
  { "id": 30, "name": "Pasta - Ravioli", "price": 10.35, "stock": 7 }
];